server:
  port: 8099

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rabbit_test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: Root@123
  rabbitmq:
    host: 192.168.171.113
    username: admin
    password: admin
    port: 5672

  application:
    name: rabbitmq-test

  banner:
    location: banner

  mvc:
    static-path-pattern: classpath:/templates/

mybatis:
  type-aliases-package: com.example.demo.mapper
  mapper-locations: /mappers/*.xml