CREATE TABLE t_user(
	ID INT AUTO_INCREMENT PRIMARY KEY, 
	username VARCHAR(255) NOT NULL, 
	password VARCHAR(255) NOT NULL, 
	email VARCHAR(255) NOT NULL, 
	head_img VARCHAR(255) NOT NULL
);

CREATE TABLE t_files (
	ID INT AUTO_INCREMENT PRIMARY KEY, 
	USER_ID INTEGER NOT NULL, 
	FILE_NAME VARCHAR(255) NOT NULL, 
	SUBMIT_FILE_NAME VARCHAR(255) NOT NULL, 
	is_dir int(1) NOT NULL, 
	path_name VARCHAR(255) NOT NULL
);
