spring:
  # redis 配置
  redis:
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    host: 127.0.0.1
    database: 0
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 300
        # 连接池中的最小空闲连接
        max-idle: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
        # 连接超时时间（毫秒）
        timeout: 5000

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ssm?serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 80
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.icloudit.demo02redistemplate.entity
