server:
  port: 9400
#注册到Eureka服务中心
eureka:
  client:
    service-url:
      defaultZone: http://demoCloudEurekaServerA:9200/eureka,http://demoCloudEurekaServerB:9201/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
spring:
  application:
    name: demo-service-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gitwu/demo-config.git  #配置git服务地址
          username: gitwu #配置git用户名
          password: 123456 #配置git密码
          search-paths:
            - demo-config
      # 读取分支
      label: master
  rabbitmq:
    host: 192.169.200.128
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"